USE [master]
GO

/****** Object:  Database [ONLINE_STORE]    Script Date: 2020-05-27 6:57:52 PM ******/
CREATE DATABASE [ONLINE_STORE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ONLINE_STORE', FILENAME = N'I:\DEV\BNC\Chris\MSSQL14.SQLEXPRESS\MSSQL\DATA\ONLINE_STORE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ONLINE_STORE_log', FILENAME = N'I:\DEV\BNC\Chris\MSSQL14.SQLEXPRESS\MSSQL\DATA\ONLINE_STORE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ONLINE_STORE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ONLINE_STORE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET ARITHABORT OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ONLINE_STORE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ONLINE_STORE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ONLINE_STORE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ONLINE_STORE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ONLINE_STORE] SET  MULTI_USER 
GO

ALTER DATABASE [ONLINE_STORE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ONLINE_STORE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ONLINE_STORE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ONLINE_STORE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ONLINE_STORE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ONLINE_STORE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ONLINE_STORE] SET  READ_WRITE 
GO

